### ISSUE TITLE
I can reset my password even if I'm not logged in by using a direct URL.

### ISSUE THREAD

**Issue by Nantawat6510545543** [Marvel-Universe/MarvelUniverse#87]
![image](https://github.com/Marvel-Universe/MarvelUniverse/assets/114897362/458a697f-496e-4d7f-9e5d-886e6a66596e)

**Comment by Sankrub** [comment]
You mean the reset email send to you even you not register? Or what I don't understand can you give me more image or more explanation. Thank you.

**Comment by Nantawat6510545543** [comment]
Password reset should only be allowed for logged in users.
It seems unusual to have a user who is not logged in submit a password reset request without even having an ID.
I think the password reset page should only be accessible to logged in users.

**Comment by Sankrub** [comment]
So you mean only logged in users can reset password right? But for my opinion is that user who is not login but do registered 
can reset the password too. For example if they forget their password so they can reset their password without login(actually they can't login because forget password that why they have to reset password). So I think even though user not login they can click to reset password page. If I miss understand something please tell me. Thanks
